services:
  stock-market-app:
    build: ./stock-market
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=stock_market
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_market
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
